name: make-image

on:
  push:
    tags:
      - 'release*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: flyer1/china-travel:latest
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "43.153.91.198"
          REMOTE_USER: "root"
        run: |
          echo "$SSH_PRIVATE_KEY" > github.pem
          chmod 400 github.pem
          ssh -i github.pem $REMOTE_USER@$REMOTE_HOST 'echo "Hello, World!"'
          rm -rf github.pem
      
        
