name: make-image

on: 
  push:
    tags:
      - 'release*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: flyer1/china-travel:latest
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_SSH_PEM }}
          REMOTE_HOST: "43.153.91.198"
          REMOTE_USER: "root"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > github.pem
          chmod 400 github.pem
          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
          ssh -i github.pem $REMOTE_USER@$REMOTE_HOST '{
            docker pull flyer1/china-travel&&
            docker stop china-travel 2>>error.log
            docker rm china-travel-old 2>>error.log
            docker rename china-travel 2>>china-travel-old
            docker run -d -p 3000:3000 --name china-travel flyer1/china-travel
          }'
          
      
        
