name: make-image

on:
  push:
    tags:
      - 'release*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: flyer1/china-travel:latest
      -
        name: SSH
        run: |
          echo ${{ secrets.TENCENT_SSH_PEM }} > github.pem
          chmod 400 github.pem
          ssh -i github.pem root@43.153.91.198
          ls
          pwd
          docker pull flyer1/china-travel
          docker run flyer1/china-travel
